# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='Введи ФИО тут', max_length=300)),
                ('birth_date', models.DateField(default=django.utils.timezone.now)),
                ('last_work', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(default='Почту@тут.введи', max_length=254)),
                ('mobile', models.CharField(default='Мобильник', max_length=10)),
                ('contra', models.TextField(default='Противопоказания')),
                ('pros', models.IntegerField(default=0)),
                ('cons', models.IntegerField(default=0)),
                ('additional', models.TextField(default='Всякие примечания')),
                ('photo', models.FileField(upload_to='peoples/')),
            ],
        ),
    ]
