# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.IntegerField(default=0)),
                ('photo', models.FileField(upload_to='works/%Y/%m/%d')),
            ],
        ),
    ]
