# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client',
            field=models.CharField(default='Выбери клиента', max_length=300),
        ),
    ]
