# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_work_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.FilePathField(path='works/%Y/%m/%d'),
        ),
    ]
