# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_work_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.FileField(upload_to="works/%Y/%m/%d/%<class 'django.db.models.fields.UUIDField'>"),
        ),
    ]
