# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:35
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170407_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
