# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170407_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.FileField(upload_to='works/%Y/%m/%d/<function user_directory_path at 0x7f69c563eb70>'),
        ),
    ]
