# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170407_2142'),
        ('core', '0008_photo_client_id'),
    ]

    operations = [
    ]
