# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20170412_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.FilePathField(path='works/%Y/%m/%d'),
        ),
    ]
