# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170412_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='client_id',
        ),
    ]
