# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170412_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
