# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170412_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
