# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170412_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
