# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170414_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
