# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170414_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Выбери категорию', max_length=300)),
            ],
        ),
    ]
