# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170415_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='work',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
