# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_photo_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='work',
        ),
    ]
