# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170424_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='photo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, upload_to='photos/%Y/'),
        ),
    ]
